apiVersion: v1
kind: ConfigMap
metadata:
  name: draughtsman-eventer
  namespace: draughtsman
data:
  config.yaml: |
    server:
      listen:
        address: 'http://0.0.0.0:8000'
    service:
      eventer:
        github:
          environment: '{{ .Values.Installation.V1.GiantSwarm.DraughtsmanEventer.Eventer.Github.Environment }}'
          organisation: '{{ .Values.Installation.V1.GiantSwarm.DraughtsmanEventer.Eventer.Github.Organisation }}'
          projects: '{{ .Values.Installation.V1.GiantSwarm.DraughtsmanEventer.Eventer.Github.Projects }}'
      kubernetes:
        incluster: true
