apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: draughtsman-eventer-secret
  namespace: draughtsman-eventer
data:
  secret.yaml: {{ .Values.Installation.V1.Secret.DraughtsmanEventer.SecretYaml | b64enc | quote }}
