apiVersion: v1
kind: Service
metadata:
  name: draughtsman-eventer
  namespace: draughtsman
  labels:
    app: draughtsman-eventer
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "8000"
spec:
  ports:
    - name: draughtsman-eventer
      port: 8000
      targetPort: 8000
  selector:
    app: draughtsman-eventer
